// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmsBus.Web.Data;

#nullable disable

namespace SmsBus.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306032339_AddColumnComments")]
    partial class AddColumnComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmsBus.Web.Entities.BalanceTransaction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("雪花ID");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasComment("金额(正=充值/退款,负=消费)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("删除时间");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasComment("描述");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasComment("软删除标记");

                    b.Property<long?>("OperatorId")
                        .HasColumnType("bigint")
                        .HasComment("操作人ID(管理员充值时)");

                    b.Property<long?>("RelatedOrderId")
                        .HasColumnType("bigint")
                        .HasComment("关联订单ID");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("类型: recharge/purchase/refund");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("用户ID");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("RelatedOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("balance_transactions", null, t =>
                        {
                            t.HasComment("余额流水表");
                        });
                });

            modelBuilder.Entity("SmsBus.Web.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("雪花ID");

                    b.Property<int?>("ActivationNumberId")
                        .HasColumnType("int")
                        .HasComment("临时接码上游号码ID");

                    b.Property<long?>("AssignedBy")
                        .HasColumnType("bigint")
                        .HasComment("管理员分配时的操作人ID");

                    b.Property<bool>("AutoSubscribe")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否自动续费");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("完成时间");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasComment("上游实际扣款(USD,balance-diff)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext")
                        .HasComment("国家代码");

                    b.Property<string>("CountryName")
                        .HasColumnType("longtext")
                        .HasComment("国家名称");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("删除时间");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("到期时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasComment("软删除标记");

                    b.Property<decimal>("ListPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasComment("上游查询商品价(USD,未折扣)");

                    b.Property<decimal>("MarkupAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasComment("加价金额(USD)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("模式: activation/rental");

                    b.Property<DateTime?>("NextRenewalAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("下次续费时间");

                    b.Property<string>("Number")
                        .HasColumnType("longtext")
                        .HasComment("手机号码");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("业务订单号(act_/rent_前缀)");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("购买时间");

                    b.Property<DateTime?>("RenewalFailedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("续费失败时间(null=正常)");

                    b.Property<int?>("RentalDcount")
                        .HasColumnType("int")
                        .HasComment("租赁时长数量");

                    b.Property<string>("RentalDtype")
                        .HasColumnType("longtext")
                        .HasComment("租赁时长类型(month/week等)");

                    b.Property<int?>("RentalOrderId")
                        .HasColumnType("int")
                        .HasComment("租赁上游订单ID");

                    b.Property<string>("ServiceCode")
                        .HasColumnType("longtext")
                        .HasComment("服务代码");

                    b.Property<string>("ServiceName")
                        .HasColumnType("longtext")
                        .HasComment("服务名称");

                    b.Property<string>("SmsContent")
                        .HasColumnType("longtext")
                        .HasComment("最新短信内容");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("来源: user/admin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("状态: waiting/activating/active/received/cancelled/expired");

                    b.Property<int?>("SubscriptionMonths")
                        .HasColumnType("int")
                        .HasComment("总订阅月数(1/3/6/12)");

                    b.Property<int>("SubscriptionRenewedCount")
                        .HasColumnType("int")
                        .HasComment("已续费次数(0=首月)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasComment("用户实付(USD)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("所属用户ID(NULL=未分配)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("longtext")
                        .HasComment("提取的验证码");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasComment("订单表");
                        });
                });

            modelBuilder.Entity("SmsBus.Web.Entities.OrderSms", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("雪花ID");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasComment("提取的验证码");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("删除时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasComment("软删除标记");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasComment("关联订单ID");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("接收时间");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("短信全文");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("order_sms", null, t =>
                        {
                            t.HasComment("订单短信记录表");
                        });
                });

            modelBuilder.Entity("SmsBus.Web.Entities.PricingConfig", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("固定ID=1");

                    b.Property<decimal>("ActivationProfitPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("临时接码商品利润百分比");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("删除时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasComment("软删除标记");

                    b.Property<bool>("MarkupEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否启用加价");

                    b.Property<decimal>("RentalProfitPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("租赁商品利润百分比");

                    b.Property<decimal>("ServiceFee12m")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("12个月服务费百分比");

                    b.Property<decimal>("ServiceFee1m")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("1个月服务费百分比");

                    b.Property<decimal>("ServiceFee3m")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("3个月服务费百分比");

                    b.Property<decimal>("ServiceFee6m")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasComment("6个月服务费百分比");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间");

                    b.Property<decimal>("UsdCnyRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasComment("USD/CNY汇率");

                    b.HasKey("Id");

                    b.ToTable("pricing_config", null, t =>
                        {
                            t.HasComment("定价配置表(单行)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActivationProfitPercent = 0m,
                            IsDeleted = false,
                            MarkupEnabled = false,
                            RentalProfitPercent = 0m,
                            ServiceFee12m = 0m,
                            ServiceFee1m = 0m,
                            ServiceFee3m = 0m,
                            ServiceFee6m = 0m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsdCnyRate = 7.25m
                        });
                });

            modelBuilder.Entity("SmsBus.Web.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("雪花ID");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasComment("账户余额(USD)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("注册时间");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("删除时间");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext")
                        .HasComment("显示名称");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否启用");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否管理员");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasComment("软删除标记");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("密码哈希(BCrypt)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("手机号（登录账号）");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("用户表");
                        });
                });

            modelBuilder.Entity("SmsBus.Web.Entities.BalanceTransaction", b =>
                {
                    b.HasOne("SmsBus.Web.Entities.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmsBus.Web.Entities.Order", "RelatedOrder")
                        .WithMany()
                        .HasForeignKey("RelatedOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmsBus.Web.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("RelatedOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmsBus.Web.Entities.Order", b =>
                {
                    b.HasOne("SmsBus.Web.Entities.User", "Assigner")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmsBus.Web.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assigner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmsBus.Web.Entities.OrderSms", b =>
                {
                    b.HasOne("SmsBus.Web.Entities.Order", "Order")
                        .WithMany("SmsList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SmsBus.Web.Entities.Order", b =>
                {
                    b.Navigation("SmsList");
                });
#pragma warning restore 612, 618
        }
    }
}
